#ifndef XPARAMETERS_ADS9V2_H   /* prevent circular inclusions */
#define XPARAMETERS_ADS9V2_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MBPROC_MB */
#define XPAR_MBPROC_MB_ADDR_SIZE 32
#define XPAR_MBPROC_MB_ADDR_TAG_BITS 0
#define XPAR_MBPROC_MB_ALLOW_DCACHE_WR 1
#define XPAR_MBPROC_MB_ALLOW_ICACHE_WR 1
#define XPAR_MBPROC_MB_AREA_OPTIMIZED 0
#define XPAR_MBPROC_MB_ASYNC_INTERRUPT 1
#define XPAR_MBPROC_MB_ASYNC_WAKEUP 3
#define XPAR_MBPROC_MB_AVOID_PRIMITIVES 0
#define XPAR_MBPROC_MB_BASE_VECTORS 0x0000000000000000
#define XPAR_MBPROC_MB_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MBPROC_MB_CACHE_BYTE_SIZE 8192
#define XPAR_MBPROC_MB_DADDR_SIZE 32
#define XPAR_MBPROC_MB_DATA_SIZE 32
#define XPAR_MBPROC_MB_DCACHE_ADDR_TAG 0
#define XPAR_MBPROC_MB_DCACHE_ALWAYS_USED 0
#define XPAR_MBPROC_MB_DCACHE_BASEADDR 0x00000000
#define XPAR_MBPROC_MB_DCACHE_BYTE_SIZE 8192
#define XPAR_MBPROC_MB_DCACHE_DATA_WIDTH 0
#define XPAR_MBPROC_MB_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MBPROC_MB_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MBPROC_MB_DCACHE_LINE_LEN 4
#define XPAR_MBPROC_MB_DCACHE_USE_WRITEBACK 0
#define XPAR_MBPROC_MB_DCACHE_VICTIMS 0
#define XPAR_MBPROC_MB_DC_AXI_MON 0
#define XPAR_MBPROC_MB_DEBUG_COUNTER_WIDTH 32
#define XPAR_MBPROC_MB_DEBUG_ENABLED 1
#define XPAR_MBPROC_MB_DEBUG_EVENT_COUNTERS 5
#define XPAR_MBPROC_MB_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MBPROC_MB_DEBUG_INTERFACE 0
#define XPAR_MBPROC_MB_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MBPROC_MB_DEBUG_PROFILE_SIZE 0
#define XPAR_MBPROC_MB_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MBPROC_MB_DEBUG_TRACE_SIZE 8192
#define XPAR_MBPROC_MB_DIV_ZERO_EXCEPTION 0
#define XPAR_MBPROC_MB_DP_AXI_MON 0
#define XPAR_MBPROC_MB_DYNAMIC_BUS_SIZING 0
#define XPAR_MBPROC_MB_D_AXI 1
#define XPAR_MBPROC_MB_D_LMB 1
#define XPAR_MBPROC_MB_D_LMB_MON 0
#define XPAR_MBPROC_MB_ECC_USE_CE_EXCEPTION 0
#define XPAR_MBPROC_MB_EDGE_IS_POSITIVE 1
#define XPAR_MBPROC_MB_ENABLE_DISCRETE_PORTS 0
#define XPAR_MBPROC_MB_ENDIANNESS 1
#define XPAR_MBPROC_MB_FAULT_TOLERANT 0
#define XPAR_MBPROC_MB_FPU_EXCEPTION 0
#define XPAR_MBPROC_MB_FREQ 100000000
#define XPAR_MBPROC_MB_FSL_EXCEPTION 0
#define XPAR_MBPROC_MB_FSL_LINKS 0
#define XPAR_MBPROC_MB_IADDR_SIZE 32
#define XPAR_MBPROC_MB_ICACHE_ALWAYS_USED 0
#define XPAR_MBPROC_MB_ICACHE_BASEADDR 0x00000000
#define XPAR_MBPROC_MB_ICACHE_DATA_WIDTH 0
#define XPAR_MBPROC_MB_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MBPROC_MB_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MBPROC_MB_ICACHE_LINE_LEN 4
#define XPAR_MBPROC_MB_ICACHE_STREAMS 0
#define XPAR_MBPROC_MB_ICACHE_VICTIMS 0
#define XPAR_MBPROC_MB_IC_AXI_MON 0
#define XPAR_MBPROC_MB_ILL_OPCODE_EXCEPTION 0
#define XPAR_MBPROC_MB_IMPRECISE_EXCEPTIONS 0
#define XPAR_MBPROC_MB_INSTR_SIZE 32
#define XPAR_MBPROC_MB_INTERCONNECT 2
#define XPAR_MBPROC_MB_INTERRUPT_IS_EDGE 0
#define XPAR_MBPROC_MB_INTERRUPT_MON 0
#define XPAR_MBPROC_MB_IP_AXI_MON 0
#define XPAR_MBPROC_MB_I_AXI 0
#define XPAR_MBPROC_MB_I_LMB 1
#define XPAR_MBPROC_MB_I_LMB_MON 0
#define XPAR_MBPROC_MB_LOCKSTEP_MASTER 0
#define XPAR_MBPROC_MB_LOCKSTEP_SELECT 0
#define XPAR_MBPROC_MB_LOCKSTEP_SLAVE 0
#define XPAR_MBPROC_MB_M0_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M1_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M2_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M3_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M4_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M5_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M6_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M7_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M8_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M9_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M10_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M11_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M12_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M13_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M14_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_M15_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_MMU_DTLB_SIZE 4
#define XPAR_MBPROC_MB_MMU_ITLB_SIZE 2
#define XPAR_MBPROC_MB_MMU_PRIVILEGED_INSTR 0
#define XPAR_MBPROC_MB_MMU_TLB_ACCESS 3
#define XPAR_MBPROC_MB_MMU_ZONES 16
#define XPAR_MBPROC_MB_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MBPROC_MB_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MBPROC_MB_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MBPROC_MB_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MBPROC_MB_M_AXI_DC_USER_VALUE 31
#define XPAR_MBPROC_MB_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MBPROC_MB_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MBPROC_MB_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MBPROC_MB_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MBPROC_MB_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MBPROC_MB_M_AXI_IC_USER_VALUE 31
#define XPAR_MBPROC_MB_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MBPROC_MB_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MBPROC_MB_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MBPROC_MB_NUMBER_OF_PC_BRK 1
#define XPAR_MBPROC_MB_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MBPROC_MB_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MBPROC_MB_NUM_SYNC_FF_CLK 2
#define XPAR_MBPROC_MB_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MBPROC_MB_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MBPROC_MB_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MBPROC_MB_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MBPROC_MB_OPCODE_0X0_ILLEGAL 0
#define XPAR_MBPROC_MB_OPTIMIZATION 0
#define XPAR_MBPROC_MB_PC_WIDTH 32
#define XPAR_MBPROC_MB_PIADDR_SIZE 32
#define XPAR_MBPROC_MB_PVR 0
#define XPAR_MBPROC_MB_PVR_USER1 0x00
#define XPAR_MBPROC_MB_PVR_USER2 0x00000000
#define XPAR_MBPROC_MB_RESET_MSR 0x00000000
#define XPAR_MBPROC_MB_RESET_MSR_BIP 0
#define XPAR_MBPROC_MB_RESET_MSR_DCE 0
#define XPAR_MBPROC_MB_RESET_MSR_EE 0
#define XPAR_MBPROC_MB_RESET_MSR_EIP 0
#define XPAR_MBPROC_MB_RESET_MSR_ICE 0
#define XPAR_MBPROC_MB_RESET_MSR_IE 0
#define XPAR_MBPROC_MB_S0_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S1_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S2_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S3_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S4_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S5_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S6_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S7_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S8_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S9_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S10_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S11_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S12_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S13_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S14_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_S15_AXIS_DATA_WIDTH 32
#define XPAR_MBPROC_MB_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MBPROC_MB_SCO 0
#define XPAR_MBPROC_MB_TRACE 1
#define XPAR_MBPROC_MB_UNALIGNED_EXCEPTIONS 0
#define XPAR_MBPROC_MB_USE_BARREL 1
#define XPAR_MBPROC_MB_USE_BRANCH_TARGET_CACHE 1
#define XPAR_MBPROC_MB_USE_CONFIG_RESET 0
#define XPAR_MBPROC_MB_USE_DCACHE 0
#define XPAR_MBPROC_MB_USE_DIV 0
#define XPAR_MBPROC_MB_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MBPROC_MB_USE_EXT_BRK 0
#define XPAR_MBPROC_MB_USE_EXT_NM_BRK 0
#define XPAR_MBPROC_MB_USE_FPU 0
#define XPAR_MBPROC_MB_USE_HW_MUL 0
#define XPAR_MBPROC_MB_USE_ICACHE 0
#define XPAR_MBPROC_MB_USE_INTERRUPT 2
#define XPAR_MBPROC_MB_USE_MMU 0
#define XPAR_MBPROC_MB_USE_MSR_INSTR 0
#define XPAR_MBPROC_MB_USE_NON_SECURE 0
#define XPAR_MBPROC_MB_USE_PCMP_INSTR 0
#define XPAR_MBPROC_MB_USE_REORDER_INSTR 1
#define XPAR_MBPROC_MB_USE_STACK_PROTECTION 0
#define XPAR_MBPROC_MB_COMPONENT_NAME bd_mb_0
#define XPAR_MBPROC_MB_EDK_IPTYPE PROCESSOR
#define XPAR_MBPROC_MB_EDK_SPECIAL microblaze
#define XPAR_MBPROC_MB_G_TEMPLATE_LIST 0
#define XPAR_MBPROC_MB_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_ADS9V2_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 0
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 0
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 1
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 1
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME bd_mb_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/


/* Definitions for interface M_AXI_REGBUS */
#define XPAR_M_AXI_REGBUS_BASEADDR 0x20000000+0x20000000
#define XPAR_M_AXI_REGBUS_HIGHADDR 0x2000FFFF+0x20000000


/* Definitions for interface M_AXI_GT_RX_0 */
#define XPAR_M_AXI_GT_RX_0_BASEADDR 0x30000000+0x20000000
#define XPAR_M_AXI_GT_RX_0_HIGHADDR 0x3000FFFF+0x20000000


/* Definitions for interface M_AXI_GT_TX_0 */
#define XPAR_M_AXI_GT_TX_0_BASEADDR 0x30010000+0x20000000
#define XPAR_M_AXI_GT_TX_0_HIGHADDR 0x3001FFFF+0x20000000


/* Definitions for interface M_AXI_JTX_0 */
#define XPAR_M_AXI_JTX_0_BASEADDR 0x30020000+0x20000000
#define XPAR_M_AXI_JTX_0_HIGHADDR 0x3002FFFF+0x20000000


/* Definitions for interface M_AXI_JTX_1 */
#define XPAR_M_AXI_JTX_1_BASEADDR 0x30030000+0x20000000
#define XPAR_M_AXI_JTX_1_HIGHADDR 0x3003FFFF+0x20000000


/* Definitions for interface M_AXI_JRX_0 */
#define XPAR_M_AXI_JRX_0_BASEADDR 0x30040000+0x20000000
#define XPAR_M_AXI_JRX_0_HIGHADDR 0x3004FFFF+0x20000000


/* Definitions for interface M_AXI_JRX_1 */
#define XPAR_M_AXI_JRX_1_BASEADDR 0x30050000+0x20000000
#define XPAR_M_AXI_JRX_1_HIGHADDR 0x3005FFFF+0x20000000


/* Definitions for interface M_AXI_JTX_ENC_0 */
#define XPAR_M_AXI_JTX_ENC_0_BASEADDR 0x30100000+0x20000000
#define XPAR_M_AXI_JTX_ENC_0_HIGHADDR 0x3010FFFF+0x20000000


/* Definitions for interface M_AXI_HMC_I2C */
#define XPAR_M_AXI_HMC_I2C_BASEADDR 0x44AA0000
#define XPAR_M_AXI_HMC_I2C_HIGHADDR 0x44AAFFFF


/* Definitions for interface M_AXI_HMC_CTRL_0 */
#define XPAR_M_AXI_HMC_CTRL_0_BASEADDR 0x44AB0000
#define XPAR_M_AXI_HMC_CTRL_0_HIGHADDR 0x44ABFFFF


/* Definitions for interface M_AXI_HMC_CTRL_1 */
#define XPAR_M_AXI_HMC_CTRL_1_BASEADDR 0x44AC0000
#define XPAR_M_AXI_HMC_CTRL_1_HIGHADDR 0x44ACFFFF


/* Definitions for interface M_AXI_TX_DMA_CTRL_0 */
#define XPAR_M_AXI_TX_DMA_CTRL_0_BASEADDR 0x44AE0000
#define XPAR_M_AXI_TX_DMA_CTRL_0_HIGHADDR 0x44AEFFFF


/* Definitions for interface M_AXI_TX_DMA_CTRL_1 */
#define XPAR_M_AXI_TX_DMA_CTRL_1_BASEADDR 0x44AF0000
#define XPAR_M_AXI_TX_DMA_CTRL_1_HIGHADDR 0x44AFFFFF


/* Definitions for interface M_AXI_RX_DMA_CTRL_0 */
#define XPAR_M_AXI_RX_DMA_CTRL_0_BASEADDR 0x44B00000
#define XPAR_M_AXI_RX_DMA_CTRL_0_HIGHADDR 0x44B0FFFF


/* Definitions for interface M_AXI_RX_DMA_CTRL_1 */
#define XPAR_M_AXI_RX_DMA_CTRL_1_BASEADDR 0x44B10000
#define XPAR_M_AXI_RX_DMA_CTRL_1_HIGHADDR 0x44B1FFFF


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 3U

/* Definitions for peripheral MBPROC_L0CACHE_DLMB_BRAM_CTL */
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_DEVICE_ID 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_DATA_WIDTH 32U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_ECC 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_FAULT_INJECT 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_CE_FAILING_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_UE_FAILING_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_ECC_STATUS_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_CE_COUNTER_WIDTH 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_ECC_ONOFF_REGISTER 0U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_WRITE_ACCESS 2U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_BASEADDR 0x00000000U
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_HIGHADDR 0x0001FFFFU
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU 
#define XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU 


/* Definitions for peripheral MBPROC_L0CACHE_ILMB_BRAM_CTL */
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_DEVICE_ID 1U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_DATA_WIDTH 32U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_ECC 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_FAULT_INJECT 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_CE_FAILING_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_UE_FAILING_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_ECC_STATUS_REGISTERS 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_CE_COUNTER_WIDTH 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_ECC_ONOFF_REGISTER 0U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_WRITE_ACCESS 2U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_BASEADDR 0x00000000U
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_HIGHADDR 0x0001FFFFU
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU 
#define XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU 


/* Definitions for peripheral PERIPHSYS_SCRATCH_MEM_CTRL */
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_DEVICE_ID 2U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_DATA_WIDTH 32U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_ECC 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_FAULT_INJECT 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_CE_FAILING_REGISTERS 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_UE_FAILING_REGISTERS 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_ECC_STATUS_REGISTERS 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_CE_COUNTER_WIDTH 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_ECC_ONOFF_REGISTER 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_WRITE_ACCESS 0U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_S_AXI_BASEADDR 0x44A80000U
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_S_AXI_HIGHADDR 0x44A87FFFU
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU 
#define XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU 


/******************************************************************/

/* Canonical definitions for peripheral MBPROC_L0CACHE_DLMB_BRAM_CTL */
#define XPAR_BRAM_0_DEVICE_ID XPAR_MBPROC_L0CACHE_DLMB_BRAM_CTL_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_0_WRITE_ACCESS 2U
#define XPAR_BRAM_0_BASEADDR 0x00000000U
#define XPAR_BRAM_0_HIGHADDR 0x0001FFFFU

/* Canonical definitions for peripheral MBPROC_L0CACHE_ILMB_BRAM_CTL */
#define XPAR_BRAM_1_DEVICE_ID XPAR_MBPROC_L0CACHE_ILMB_BRAM_CTL_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x0001FFFFU

/* Canonical definitions for peripheral PERIPHSYS_SCRATCH_MEM_CTRL */
#define XPAR_BRAM_2_DEVICE_ID XPAR_PERIPHSYS_SCRATCH_MEM_CTRL_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32U
#define XPAR_BRAM_2_ECC 0U
#define XPAR_BRAM_2_FAULT_INJECT 0U
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_2_WRITE_ACCESS 0U
#define XPAR_BRAM_2_BASEADDR 0x44A80000U
#define XPAR_BRAM_2_HIGHADDR 0x44A87FFFU


/******************************************************************/

/* Definitions for driver CLK_WIZ */
#define XPAR_XCLK_WIZ_NUM_INSTANCES 1

/* Definitions for peripheral CLKRSTSYS_CLK_SPI_ADJ */
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_DEVICE_ID 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_BASEADDR 0x44A70000
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_HIGHADDR 0x44A7FFFF
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_USER_CLOCK0 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_USER_CLOCK1 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_USER_CLOCK2 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_USER_CLOCK3 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_REF_CLK_FREQ 100.0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_USER_CLK_FREQ0 100.0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_USER_CLK_FREQ1 100.0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_USER_CLK_FREQ2 100.0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_USER_CLK_FREQ3 100.0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_PRECISION 1
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_PLL0 0
#define XPAR_CLKRSTSYS_CLK_SPI_ADJ_ENABLE_PLL1 0


/******************************************************************/

/* Canonical definitions for peripheral CLKRSTSYS_CLK_SPI_ADJ */
#define XPAR_CLK_WIZ_0_DEVICE_ID XPAR_CLKRSTSYS_CLK_SPI_ADJ_DEVICE_ID
#define XPAR_CLK_WIZ_0_BASEADDR 0x44A70000
#define XPAR_CLK_WIZ_0_HIGHADDR 0x44A7FFFF
#define XPAR_CLK_WIZ_0_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_0_REF_CLK_FREQ 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ0 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ1 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ2 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ3 100.0
#define XPAR_CLK_WIZ_0_PRECISION 1
#define XPAR_CLK_WIZ_0_Enable_PLL0 0
#define XPAR_CLK_WIZ_0_Enable_PLL1 0


/******************************************************************/


/* Definitions for peripheral PERIPHSYS_I2C_MUX */
#define XPAR_PERIPHSYS_I2C_MUX_BASEADDR 0x44A10000
#define XPAR_PERIPHSYS_I2C_MUX_HIGHADDR 0x44A1FFFF


/* Definitions for peripheral PERIPHSYS_SPI */
#define XPAR_PERIPHSYS_SPI_BASEADDR 0x44A00000
#define XPAR_PERIPHSYS_SPI_HIGHADDR 0x44A0FFFF


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 7
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MBPROC_MB_INTC */
#define XPAR_MBPROC_MB_INTC_DEVICE_ID 0
#define XPAR_MBPROC_MB_INTC_BASEADDR 0x44A90000
#define XPAR_MBPROC_MB_INTC_HIGHADDR 0x44A9FFFF
#define XPAR_MBPROC_MB_INTC_KIND_OF_INTR 0xFFFFFF80
#define XPAR_MBPROC_MB_INTC_HAS_FAST 1
#define XPAR_MBPROC_MB_INTC_IVAR_RESET_VALUE 0x00000010
#define XPAR_MBPROC_MB_INTC_NUM_INTR_INPUTS 7


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x44A90000
#define XPAR_INTC_SINGLE_HIGHADDR 0x44A9FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_MBPROC_MB_INTC_DEVICE_ID
#define XPAR_MBPROC_MB_INTC_TYPE 0U
#define XPAR_PERIPHSYS_SYSMON_IP2INTC_IRPT_MASK 0X000001U
#define XPAR_MBPROC_MB_INTC_PERIPHSYS_SYSMON_IP2INTC_IRPT_INTR 0U
#define XPAR_PERIPHSYS_TIMER_INTERRUPT_MASK 0X000002U
#define XPAR_MBPROC_MB_INTC_PERIPHSYS_TIMER_INTERRUPT_INTR 1U
#define XPAR_SYSTEM_REGMAP_IRQ_MASK 0X000004U
#define XPAR_MBPROC_MB_INTC_SYSTEM_REGMAP_IRQ_INTR 2U
#define XPAR_SYSTEM_TX_DMA_0_IRQ_MASK 0X000008U
#define XPAR_MBPROC_MB_INTC_SYSTEM_TX_DMA_0_IRQ_INTR 3U
#define XPAR_SYSTEM_TX_DMA_1_IRQ_MASK 0X000010U
#define XPAR_MBPROC_MB_INTC_SYSTEM_TX_DMA_1_IRQ_INTR 4U
#define XPAR_SYSTEM_RX_DMA_0_IRQ_MASK 0X000020U
#define XPAR_MBPROC_MB_INTC_SYSTEM_RX_DMA_0_IRQ_INTR 5U
#define XPAR_SYSTEM_RX_DMA_1_IRQ_MASK 0X000040U
#define XPAR_MBPROC_MB_INTC_SYSTEM_RX_DMA_1_IRQ_INTR 6U

/******************************************************************/

/* Canonical definitions for peripheral MBPROC_MB_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_MBPROC_MB_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x44A90000U
#define XPAR_INTC_0_HIGHADDR 0x44A9FFFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFF80U
#define XPAR_INTC_0_HAS_FAST 1U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x00000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 7U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_SYSMON_0_VEC_ID XPAR_MBPROC_MB_INTC_PERIPHSYS_SYSMON_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_TMRCTR_0_VEC_ID XPAR_MBPROC_MB_INTC_PERIPHSYS_TIMER_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver SYSMON */
#define XPAR_XSYSMON_NUM_INSTANCES 1U

/* Definitions for peripheral PERIPHSYS_SYSMON */
#define XPAR_PERIPHSYS_SYSMON_IP_TYPE 1U
#define XPAR_PERIPHSYS_SYSMON_DEVICE_ID 0U
#define XPAR_PERIPHSYS_SYSMON_BASEADDR 0x44A20000U
#define XPAR_PERIPHSYS_SYSMON_HIGHADDR 0x44A2FFFFU
#define XPAR_PERIPHSYS_SYSMON_INCLUDE_INTR 1U


/******************************************************************/

/* Canonical definitions for peripheral PERIPHSYS_SYSMON */
#define XPAR_SYSMON_0_IP_TYPE 1U
#define XPAR_SYSMON_0_DEVICE_ID XPAR_PERIPHSYS_SYSMON_DEVICE_ID
#define XPAR_SYSMON_0_BASEADDR 0x44A20000U
#define XPAR_SYSMON_0_HIGHADDR 0x44A2FFFFU
#define XPAR_SYSMON_0_INCLUDE_INTR 1U


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1U

/* Definitions for peripheral PERIPHSYS_TIMER */
#define XPAR_PERIPHSYS_TIMER_DEVICE_ID 0U
#define XPAR_PERIPHSYS_TIMER_BASEADDR 0x44A40000U
#define XPAR_PERIPHSYS_TIMER_HIGHADDR 0x44A4FFFFU
#define XPAR_PERIPHSYS_TIMER_CLOCK_FREQ_HZ 50000000U


/******************************************************************/

/* Canonical definitions for peripheral PERIPHSYS_TIMER */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x44A40000U
#define XPAR_TMRCTR_0_HIGHADDR 0x44A4FFFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_PERIPHSYS_TIMER_CLOCK_FREQ_HZ

/******************************************************************/

#endif  /* end of protection macro */
