/*!
 * \brief     Configure and run Multi Chip Sync Calibration on Apollo B0
 *
 * The example demonstrates Apollo's MCS calibration procedure.
 * The procedure consists of running MCS init calibration for coarse alignment of Apollo's internal SYSREF against the provided external SYSREF.
 * Following init cal, one can continue the adjustment by performing MCS tracking calibration to further fine tune the time difference between
 * the internal and external SYSREF interval.
 *
 * MCS Init Cal provides a SYSREF alignment of +/- 0.5 Device Clk cycles and can be executed with SYSREF generated by external source like SigGen.
 * The Init Cal performs alignment once when it's executed and does not track the drift between the two SYSREFs over time.
 *
 * MCS Tracking Cal requires the use of ADF4382 as Device Clk source.
 * MCS Tracking cal can achieve precision in orders of pico-seconds depending on correct SYSREF interval and decimation settings.
 * Tracking cal can also periodically send correction strobes to ADF4382 to correct clock drifts over time and temperature.
 *
 * The examples also shows how to configure ADF4030 as SYSREF clock source for an in-system clocking setup.
 *
 * To ensure easy of understanding and adoption, the example is divided into steps one can follow based on their system requirements.
 *
 *
 * \copyright copyright(c) 2024 analog devices, inc. all rights reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "adi_apollo.h"
#include "adi_fpga_apollo_types.h"
#include "apollo_cpu_device_profile_types.h"
#include "adi_ads10_apollo_ex_mcs.h"
#include "adi_ads10_apollo_ex_cal.h"
#include "ads10_fpga.h"

#define EN_DEBUG                        0
#define DEBUG_PRINT(func, enable)       if (enable == 1) { func; }


int32_t mcs_cal(adi_apollo_device_t *device, adi_fpga_apollo_device_t *fpga_device, adi_apollo_top_t *profile, int argc, char *argv[], int argc_ofst)
{
    int32_t err = 0;
    uint8_t i = 0;

    // Example Flow Control Flags
    bool use_adf4030_sysref_src = true;             // Flag to enable onboard SYSREF clock generation using ADF4030
    bool use_adf4382_mcs_tracking_cal = true;       // Flag to enable MCS tracking calibration by periodic signalling DELADJ and DELSTR pins of ADF4382
    bool allow_adf4382_coarse_adjustment = true;    // Flag to allow adjustment of ADF4382's Coarse Bleed Current DAC
    bool abort_cal = false;                         // Flag to abort MCS cal

    // MCS Calibration Data Variables
    uint64_t dev_clk_hz = (uint64_t) profile->clk_cfg.dev_clk_freq_kHz * 1e3;
    uint64_t adf4382_ref_freq_hz = 125e6;
    uint64_t adf4382_rfout_freq_hz = dev_clk_hz;
    uint8_t divg_modulus = (profile->clk_cfg.clocking_mode == 0) ? 8 : 4;   // divg is global digital divider
    uint32_t sysref_prd_digclk_cycles = profile->mcs_cfg.internal_sysref_prd_digclk_cycles_center;
    double int_sysref_freq_hz = (double) (dev_clk_hz) / (divg_modulus * sysref_prd_digclk_cycles);
    uint64_t ext_sysref_freq_hz = (uint64_t) (int_sysref_freq_hz);
    printf("Sysref Freq (%f Hz) Supported: %s.\n", int_sysref_freq_hz, ((int_sysref_freq_hz == ext_sysref_freq_hz) ? "True" : "False"));

    uint8_t fpga_ref_div = (profile->jtx[0].common_link_cfg.ver == ADI_APOLLO_JESD_204C) ? 66 : 40;
    uint64_t fpga_ref_freq_hz = profile->jtx[0].common_link_cfg.lane_rate_kHz / fpga_ref_div * 1e3;

    // Currently supporting SYSREF Freq with minimum resolution of Hz.
    ADI_CMS_CHECK((int_sysref_freq_hz != ext_sysref_freq_hz), API_CMS_ERROR_NOT_SUPPORTED);

    // MCS Init Cal
    adi_apollo_mcs_cal_init_status_t init_cal_status = {{0}};

    // MCS Tracking cal
    uint16_t mcs_tracking_decimation = 1023;
    adi_apollo_mcs_cal_status_t tracking_cal_status = {{0}};

    // ADF4382 Device Struct and Bleed Current read back
    adi_adf4382_device_t adf4382 = {{0}};
    int16_t hw_current_fine = 0;
    int8_t hw_current_coarse = 0;
    uint8_t hw_bleed_pol = 0;

    // ADF4030 Device Struct and Config
    adi_adf4030_device_t adf4030 = {{0}};
    uint8_t adf4030_dev_id = ADF4030_0;
    uint64_t bsync_out_freq_hz = ext_sysref_freq_hz;
    uint64_t adf4030_ref_freq_hz = (uint64_t) (fpga_ref_freq_hz < ADI_ADF4030_REF_FREQ_MAX) ? fpga_ref_freq_hz : (fpga_ref_freq_hz / 2);    // Generated by HMC7044. To-Do: HMC7044 to generate fixed ref clk.
    uint64_t vco_out_freq_hz = 0;
    uint16_t apollo_bsync_out_ch_sel = 0;
    uint16_t bsync_out_ch_sel = 0;
    uint16_t bsync_in_ch_sel = (1 << ADI_ADF4030_CHANNEL_ID_0);

    /* Determine Apollo SYSREF BSYNC Source based on profile clk config */
    err = adi_ads10_apollo_ex_adf4030_apollo_bsync_out_ch_get(profile, &apollo_bsync_out_ch_sel);
    ADI_CMS_ERROR_RETURN(err);

    // CH_1: Observe SYSREF, CH_8: FPGA SYSREF, Profile based Apollo SYSREF Channel
    bsync_out_ch_sel = ((1 << ADI_ADF4030_CHANNEL_ID_1) | (1 << ADI_ADF4030_CHANNEL_ID_8) | apollo_bsync_out_ch_sel);

    err = adi_ads10_apollo_ex_adf4030_vco_freq_calc(adf4030_ref_freq_hz, bsync_out_freq_hz, &vco_out_freq_hz);
    ADI_CMS_ERROR_RETURN(err);

    printf("\n");
    printf("dev_clk_hz: %lld.\t", dev_clk_hz);
    printf("divg_modulus: %d.\t sysref_prd_digclk_cycles: %d.\n", divg_modulus, sysref_prd_digclk_cycles);
    printf("Internal SysRef Freq: %f Hz.\n", int_sysref_freq_hz);
    printf("External SysRef Freq: %lld Hz.\n", ext_sysref_freq_hz);
    printf("vco_out_freq_hz: %lld Hz.\n", vco_out_freq_hz);
    printf("adf4030_ref_freq_hz: %lld Hz.\n", adf4030_ref_freq_hz);
    printf("bsync_out_freq_hz: %lld Hz.\n", bsync_out_freq_hz);
    printf("fpga_ref_freq_hz: %lld Hz.\n", fpga_ref_freq_hz);

    /* Run Clock Conditioning cal */
    err = adi_ads10_apollo_ex_cals_run(device, profile, ADI_ADS10_APOLLO_CAL_CC);
    ADI_CMS_ERROR_RETURN(err);

/*  Step: 01. Configure device struct and HAL settings for ADF4382 and ADF4030.
              If ADF4030 is SYSREF clocking source, configure its startup and input / output settings. */

    // Configure ADF4382 HAL
    err = adi_ads10_apollo_ex_adf4382_hal_config(&adf4382,
                                                 NULL,
                                                 &ads10_fpga_fmcb_aux_gpio_write);
    ADI_CMS_ERROR_RETURN(err);

    if (use_adf4030_sysref_src) {
        // Configure ADF4030 HAL.
        err = adi_ads10_apollo_ex_adf4030_configure_hal(&adf4030, adf4030_dev_id);
        ADI_CMS_ERROR_RETURN(err);

        // Perform ADF4030 power up and initialization.
        err = adi_ads10_apollo_ex_adf4030_startup(&adf4030, adf4030_ref_freq_hz, vco_out_freq_hz);
        ADI_CMS_ERROR_RETURN(err);

        // BSYNC setup for sysref generation.
        err = adi_ads10_apollo_ex_adf4030_bsync_input_set(&adf4030, bsync_in_ch_sel);
        ADI_CMS_ERROR_RETURN(err);

        err = adi_ads10_apollo_ex_adf4030_bsync_output_set(&adf4030,
                                                           bsync_out_ch_sel,
                                                           vco_out_freq_hz,
                                                           bsync_out_freq_hz, 1);
        ADI_CMS_ERROR_RETURN(err);

        // SYNC all BSYNC_OUT channels with BSYNC_IN Ref channel.
        printf("Align all BSYNC_OUT Channels with ref BSYNC_IN Channel...\n");
        err = adi_ads10_apollo_ex_adf4030_align_bsync_out(&adf4030,
                                                          bsync_in_ch_sel,
                                                          bsync_out_ch_sel,
                                                          bsync_out_freq_hz);
        ADI_CMS_ERROR_RETURN(err);

    }


/*  Step: 02. Program MCS Init Cal, including most of settings for ADF4382 Tracking.
              And configure ADF4382 for MCS init cal. */

    err = adi_ads10_apollo_ex_mcs_init_cal_setup(device,
                                                 &adf4382,
                                                 adf4382_ref_freq_hz,
                                                 adf4382_rfout_freq_hz,
                                                 ext_sysref_freq_hz);
    ADI_CMS_ERROR_RETURN(err);


/*  Step: 03. Start MCS init cal. */

    printf("Running MCS Init Calibration...\n");
    err = adi_apollo_mcs_cal_init_run(device);
    ADI_CMS_ERROR_RETURN(err);


/*  Step: 04. Read back MCS init cal status data and validate init cal success. */

    err = adi_apollo_mcs_cal_init_status_get(device, &init_cal_status);
    ADI_CMS_ERROR_RETURN(err);

    err = adi_ads10_apollo_ex_mcs_init_cal_validate(device, profile, &init_cal_status);
    ADI_CMS_ERROR_RETURN(err);

    DEBUG_PRINT(adi_ads10_apollo_ex_mcs_init_cal_status_print(&init_cal_status), EN_DEBUG)


/*  Step: 05. Start MCS tracking cal. */

    err = adi_ads10_apollo_ex_mcs_tracking_cal_setup(device, mcs_tracking_decimation, 1);
    ADI_CMS_ERROR_RETURN(err);


/*  Step: 06. Enable ADF4382 Auto Align. */

    err = adi_adf4382_phase_adjust_auto_align_enable(&adf4382, 1);
    ADI_CMS_ERROR_RETURN(err);


/*  Step: 07. Run MCS Foreground and Background Tracking Cal. */
    if (profile->clk_cfg.single_dual_clk_sel == false) {
        if (use_adf4382_mcs_tracking_cal ) {

            /* Execute MCS Foreground Tracking cal for faster SysRef Alignment.
            Performs TDC measurements and multi phase correction strobes for clock calibration. */
            printf("Running MCS FG Tracking Calibration...\n");
            err = adi_apollo_mcs_cal_fg_tracking_run(device);
            ADI_CMS_ERROR_RETURN(err);

            /* Trigger MCS Background Tracking cal for maintaining alignment.
            Executes in background periodically, taking TDC measurements and phase correction if required. */
            printf("Running MCS BG Tracking Calibration...\n");
            err = adi_apollo_mcs_cal_bg_tracking_run(device);
            ADI_CMS_ERROR_RETURN(err);


/*  Step: 08. Halt MCS Background Tracking Cal and get status info for validation. */

            for (i = 0; i < 5; ++i) {
                printf("Loop#: %02d.\n", i);

                err = adi_apollo_hal_delay_us(device, 10 * 1000000);
                ADI_CMS_ERROR_RETURN(err);

                // Halt Tracking calibration to pull data from FW.
                err = adi_apollo_mcs_cal_bg_tracking_freeze(device);
                ADI_CMS_ERROR_RETURN(err);

                // Get tracking calibration status info.
                err = adi_apollo_mcs_cal_tracking_status_get(device, &tracking_cal_status);
                ADI_CMS_ERROR_RETURN(err);

                if (i == 0) {
                    DEBUG_PRINT(adi_ads10_apollo_ex_mcs_track_cal_status_print(&tracking_cal_status, 1), EN_DEBUG)
                }

                err = adi_ads10_apollo_ex_mcs_track_cal_status_print(&tracking_cal_status, 0);
                ADI_CMS_ERROR_RETURN(err);

                err = adi_ads10_apollo_ex_adf4382_del_cnt_get(&adf4382, &hw_bleed_pol, &hw_current_coarse, &hw_current_fine);
                ADI_CMS_ERROR_RETURN(err);

                // Resume Tracking calibration.
                err = adi_apollo_mcs_cal_bg_tracking_unfreeze(device);
                ADI_CMS_ERROR_RETURN(err);

                err = adi_ads10_apollo_ex_mcs_tracking_cal_validate(device, &tracking_cal_status, hw_bleed_pol, hw_current_coarse, hw_current_fine);
                ADI_CMS_ERROR_RETURN(err);

                if ((tracking_cal_status.mcs_tracking_cal_status.track_state[0] == track_state_background_running_active_fault) && (allow_adf4382_coarse_adjustment)) {
                    if (tracking_cal_status.mcs_tracking_cal_status.adf4382_specific_status->EOR_Coarse == 1) {
                        adi_apollo_hal_log_write(device, ADI_CMS_LOG_ERR, "ADF4382 has reached the end of its correction range. Re-Initialize and run the MCS Calibration again.");
                        printf("ADF4382 has reached the end of its correction range. Re-Initialize and run the MCS Calibration again.");
                        return API_CMS_ERROR_MCS_CAL_CONFIG_ERROR;
                    } else {
                        // Perform a ADF4382 Bleed Current Coarse Adjustment.
                        printf("Allowing MCS Tracking Cal to tell ADF4382 to proceed with a Coarse adjustment.");
                        err = adi_apollo_mcs_cal_coarse_jump_set(device);
                        ADI_CMS_ERROR_RETURN(err);
                    }
                }
                printf("\n");
            }

        } else {
/*  Step: 09. Use "Forced" FG/BG MCS Tracking Cal as per system's need. */

            /* If the user does not want MCS BG Tracking cal to periodically update ADF4382 clock,
            they can only send "forced" calibration triggers as per their requirements. */

            // Optional: Send forced FG Tracking Cal command.
            err = adi_apollo_mcs_cal_force_fg_tracking_run(device);
            ADI_CMS_ERROR_RETURN(err);

            // Optional: Send forced BG Tracking Cal command.
            err = adi_apollo_mcs_cal_force_bg_tracking_run(device);
            ADI_CMS_ERROR_RETURN(err);

            // Get tracking calibration status info.
            err = adi_apollo_mcs_cal_tracking_status_get(device, &tracking_cal_status);
            ADI_CMS_ERROR_RETURN(err);

            err = adi_ads10_apollo_ex_mcs_track_cal_status_print(&tracking_cal_status, 0);
            ADI_CMS_ERROR_RETURN(err);

            err = adi_ads10_apollo_ex_adf4382_del_cnt_get(&adf4382, &hw_bleed_pol, &hw_current_coarse, &hw_current_fine);
            ADI_CMS_ERROR_RETURN(err);

            err = adi_ads10_apollo_ex_mcs_tracking_cal_validate(device, &tracking_cal_status, hw_bleed_pol, hw_current_coarse, hw_current_fine);
            ADI_CMS_ERROR_RETURN(err);
        }
    }

    // err = adi_ads10_apollo_ex_mcs_sysref_info_print(device);
    // ADI_CMS_ERROR_RETURN(err);
    err = adi_ads10_apollo_ex_mcs_sysref_phase_print(device);
    ADI_CMS_ERROR_RETURN(err);
    err = adi_ads10_apollo_ex_mcs_link_phase_print(device);
    ADI_CMS_ERROR_RETURN(err);

    if ((abort_cal) && (profile->clk_cfg.single_dual_clk_sel == false)) {
/*  Step: 10. Abort MCS Tracking Calibration. */
        printf("Aborting MCS BG Tracking Calibration...\n");
        err = adi_apollo_mcs_cal_bg_tracking_abort(device);
        ADI_CMS_ERROR_RETURN(err);
    }

    return API_CMS_ERROR_OK;
}
